title: Yu Jiang
author:
  name: Yu Jiang
  email: yu.jiang@nyu.edu

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Dr Jiang's personal website

# Build settings

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Self-contained theme (no external dependencies)

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - cv.md
  - publications.md
  - blog.md

# Set to `true` to show excerpts on the homepage.
#show_excerpts: false

# Site-specific settings
date_format: "%b %-d, %Y"


